; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for SUPERHOT BGM:

.export _music_data_superhot_bgm:=music_data_superhot_bgm

music_data_superhot_bgm:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : SUPERHOT
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_superhot_bgm
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $70 ; 00 : Arp
	.word @env3, @env2, @env2
	.byte $00
	.byte $30 ; 01 : Bass
	.word @env1, @env2, @env2
	.byte $00
	.byte $30 ; 02 : Lead
	.word @env0, @env2, @env2
	.byte $00

@env0:
	.byte $cf,$cc,$c9,$c6,$c3,$c1,$00,$05
@env1:
	.byte $cf,$7f,$00,$00
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $cc,$c8,$c4,$c1,$00,$03

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $84, $5c, $91, $5c, $91, $52, $91, $5c
@song0ref12:
	.byte $91, $62, $91, $62, $91, $5c, $91, $5c, $f9, $b7, $62, $91, $58, $91, $52, $91, $5c, $91, $5c, $91, $52, $91, $5c, $91
	.byte $5c, $f9, $b7, $5c, $91, $52, $91, $4e, $91, $52
	.byte $ff, $0c
	.word @song0ref12
@song0ref49:
	.byte $5c, $91, $62
@song0ref52:
	.byte $91, $5c, $91, $52, $91, $52, $91, $52, $91, $5c, $f9, $b7, $52, $91, $4e, $91, $4e, $91, $52, $91, $52, $91, $62, $91
	.byte $62, $91, $5c, $f9, $b7, $5c, $91
	.byte $ff, $11
	.word @song0ref49
	.byte $62, $91, $52, $91, $5c, $91, $62, $91, $5c, $91, $60, $91, $5c, $f9, $b7, $5c, $91, $52, $91, $60, $91, $62, $91, $62
	.byte $91, $60, $91, $5e, $91, $5e, $f9, $b7, $5c, $91, $5c, $91, $5c, $91, $5c, $91, $5c, $91, $5c, $91, $52, $91, $5c, $f9
	.byte $b7, $58
	.byte $ff, $09
	.word @song0ref52
	.byte $52, $91, $5c, $91, $5c, $f9, $b7, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $44
@song0ref152:
	.byte $91, $00, $91, $4a
@song0ref156:
	.byte $91, $00, $91
@song0ref159:
	.byte $52, $91, $00, $91, $4a, $91, $00, $91, $44
	.byte $ff, $0c
	.word @song0ref156
@song0ref171:
	.byte $91, $00, $91, $3a
@song0ref175:
	.byte $91, $00, $91, $44
@song0ref179:
	.byte $91, $00, $91, $4a, $91, $00, $91, $44, $91, $00, $91, $3a
	.byte $ff, $0c
	.word @song0ref179
	.byte $ff, $0b
	.word @song0ref175
	.byte $ff, $09
	.word @song0ref159
	.byte $ff, $0c
	.word @song0ref156
	.byte $ff, $0b
	.word @song0ref152
	.byte $58
	.byte $ff, $0b
	.word @song0ref156
	.byte $58
	.byte $ff, $0b
	.word @song0ref156
@song0ref214:
	.byte $4e, $91, $00, $91, $44, $91, $00, $91, $52, $91, $00, $91
	.byte $ff, $0c
	.word @song0ref214
	.byte $4e, $91, $00, $91, $44
	.byte $ff, $0b
	.word @song0ref175
	.byte $ff, $09
	.word @song0ref159
	.byte $ff, $0c
	.word @song0ref156
	.byte $ff, $14
	.word @song0ref171
	.byte $ff, $0c
	.word @song0ref179
	.byte $ff, $0b
	.word @song0ref152
	.byte $58
	.byte $ff, $0b
	.word @song0ref156
	.byte $58
	.byte $ff, $0c
	.word @song0ref156
	.byte $ff, $10
	.word @song0ref152
	.byte $ff, $0c
	.word @song0ref156
	.byte $ff, $14
	.word @song0ref171
	.byte $ff, $0c
	.word @song0ref179
	.byte $91, $00, $91, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $82
@song0ref280:
	.byte $2c, $cd, $32, $cd, $2c, $cd, $22, $cd, $2c, $cd, $22, $cd, $32
@song0ref293:
	.byte $cd, $2c, $cd, $2c, $cd, $32, $cd, $2c, $cd, $22
@song0ref303:
	.byte $cd, $32, $cd, $28, $cd, $32, $cd, $22, $cd, $36, $cd, $2c, $cd, $22
	.byte $ff, $0b
	.word @song0ref293
	.byte $2c, $cd, $22, $cd, $32, $cd, $2c
	.byte $ff, $09
	.word @song0ref303
	.byte $ff, $10
	.word @song0ref280
	.byte $fd
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
@song0ref338:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $09
	.word @song0ref338
	.byte $ff, $09
	.word @song0ref338
	.byte $f9, $f9, $cb, $fd
	.word @song0ch3loop
